compile:
	g++ multicast_twothreads_try1_same_multicast_socket_fd.cpp -o multicast_try1 -std=c++11 -pthread 
	g++ multicast_twothreads_try2_2_socket_fds.cpp -o multicast_try2 -std=c++11 -pthread 

try1:
	g++ multicast_twothreads_try1_same_multicast_socket_fd.cpp -o multicast_try1 -std=c++11 -pthread 

try2:
	g++ multicast_twothreads_try2_2_socket_fds.cpp -o multicast_try2 -std=c++11 -pthread 


clean:
	rm multicast_try1 multicast_try2  