compile:
	g++ multicast_without_ordering.cpp helper.cpp -o no_ordering -std=c++11 -pthread 

no_ordering:
	g++ multicast_without_ordering.cpp helper.cpp -o no_ordering -std=c++11 -pthread 


clean:
	rm  no_ordering