compile:
	g++ sender.cpp -o sender -std=c++11
	g++ receiver.cpp -o receiver -std=c++11

sender:
	g++ sender.cpp -o sender -std=c++11 

receiver:
	g++ receiver.cpp -o receiver -std=c++11

clean:
	rm sender receiver